networks:
  warden-network:
    driver: bridge
    name: warden-network

volumes:
  #registry-data:
  #nginx-state:
  redis-data:

services:
  warden:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warden
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- nginx-state:/nginx/state
    environment:
      - REGISTRY_TYPE=dockerhub  # dockerhub, registry, harbor, private
      - REGISTRY_URL=repo.warden.com
      - REGISTRY_USERNAME=admin
      - REGISTRY_PASSWORD=admin123
      - REDIS_DB=0
    depends_on:
      - redis
      - proxy
    networks:
      - warden-network
    restart: unless-stopped

  proxy:
    image: nginx-alpine
    container_name: proxy
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./
    networks:
      - warden-network
    depends_on:

    restart: unless-stopped
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - warden-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
