networks:
  warden-network:
    driver: bridge
    name: warden-network

volumes:
  #registry-data:
  #nginx-state:
  redis-data:

services:
  warden:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warden
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./warden/nginx/configs:/etc/nginx/configs
    environment:
      - REGISTRY_TYPE=dockerhub  # dockerhub, registry, harbor, private
      - REGISTRY_URL=repo.warden.com # MOCK private registry
      - REGISTRY_USERNAME=admin
      - REGISTRY_PASSWORD=admin123
      - AUTOMATIC_DEPLOYMENT=true # if true, the warden will automatically deploy the new image when a new image is found in the registry
      - IMAGE_NAME=demo-app
      - IMAGE_TAG=latest # default tag to use if no version is provided
      - REDIS_DB=0
      - PROXY_CONTAINER_NAME=proxy
      - PROXY_CONTAINER_TYPE=nginx  # for now, only nginx is supported
      - UPSTREAM_CONFIG=/etc/nginx/configs/upstream.conf
      - APP_NAME=demo-app       # name of the app to track deployment state
      - APP_TYPE=nextjs         # type of the app (nextjs, flask, django, fastapi, rust, golang, python, nodejs, express, ruby, php)
    depends_on:
      - redis
      - proxy
    networks:
      - warden-network
    restart: unless-stopped

  proxy:
    image: nginx-alpine
    container_name: proxy
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./warden/nginx/configs:/etc/nginx/configs
      - ./warden/nginx/nginx.conf:etc/nginx/nginx.conf
    networks:
      - warden-network
    depends_on:
      - warden
    restart: unless-stopped
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - warden-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
